version: 0.1.0                                            

name: npm-publish
description: This stack setsup a repository to publish to npmjs          

branding:                                                # stack branding 
 icon: 'package'
 color: 'black'

inputs:                                                  
  - name: NODE_VERSION                                   
    default: v12.22.4                                    
    description: NODE_VERSION for nodejs stack           
    validvalues:                                         
    - v12.22.4
    - v14.17.4

  - name: NPM_TOKEN                                   
    description: Enter the NPM_TOKEN with access to publish NPM token 
    required: true
    is-secret: true
    
  - name: NPM_PACKAGE_NAME                                   
    description: Enter the npm Package name
    required: true   
    
  - name: NPM_PACKAGE_DESCRIPTION                                   
    description: Enter the npm package name
    required: true   
    
  - name: NPM_AUTHOR                                   
    description: Enter the npm package name
    required: true   
    
  - name:  NPM_LICENSE    
    default: 'ISC'
    description: Enter the npm package license
    required: true    
    validvalues:         
    - ISC
    - MIT                                
    # - 'Academic Free License v3.0'
    # - 'Apache license 2.0'	
    # - 'Artistic license 2.0'	
    # - 'Boost Software License 1.0'	
    # - 'BSD 2-clause "Simplified" license'	
    # - 'BSD 3-clause "New" or "Revised" license'	
    # - 'BSD 3-clause Clear license'	
    # - 'Creative Commons license family	cc'
    # - 'Creative Commons Zero v1.0 Universal'
    # - 'Creative Commons Attribution 4.0'	
    # - 'Creative Commons Attribution Share Alike 4.0'	
    # - 'Do What The F*ck You Want To Public License'	
    # - 'Educational Community License v2.0'	
    # - 'Eclipse Public License 1.0'	
    # - 'Eclipse Public License 2.0'	
    # - 'European Union Public License 1.1'	
    # - 'GNU Affero General Public License v3.0'	
    # - 'GNU General Public License family'	
    # - 'GNU General Public License v2.0'	
    # - 'GNU General Public License v3.0'	
    # - 'GNU Lesser General Public License family'	
    # - 'GNU Lesser General Public License v2.1'	
    # - 'GNU Lesser General Public License v3.0'	
    # - 'ISC'	
    # - 'LaTeX Project Public License'
    # - 'Microsoft Public License'	
    # - 'MIT'	
    # - 'Mozilla Public License 2.0'	
    # - 'Open Software License 3.0'	
    # - 'PostgreSQL License'	
    # - 'SIL Open Font License 1.1'	
    # - 'University of Illinois/NCSA Open Source License'	
    # - 'The Unlicense'	
    # - 'zLib License'	
 
    
configs:
  repo-metadata:
    parameters:
      description: 'Application to publish to npmjs publish'
      secrets: 
        - name: NPM_TOKEN
          value: ${{inputs.NPM_TOKEN}}
      topics:
      - nextjs
      - npmjs

  environments:
    - name: development
      parameters:
        protected-branches: false
        allowed-branch-rules:
          - main
          - releases/*

init:
  uses: "stack-init.yaml"
